// The backtracking level's cards.
//
// A card never shows example outputs. Contestants explore through a terminal
// that prints `referenceSolution`'s output for ANY input inside `fields` - the
// same range the card displays as its constraints and the judge tests use:
//   visibleInputs - small tests; a failed one comes back with an expected/actual diff
//   hiddenInputs  - larger tests; pass/fail only
//
// Every value inside `fields` has a real answer: no card ever prints "none" or
// 0. `npm run verify:cards` checks every value against independent brute
// forces.
//
// Expected outputs are generated by running the reference, never typed by hand.
// Titles stay neutral: the rule is the thing being discovered.

import { PROBLEM_STATUS } from '../src/lib/constants.js';

const STARTER = `#include <stdio.h>

int main(void) {
    /* Read one line from stdin, print the answer to stdout. */
    return 0;
}
`;

const field = (name, min, max) => ({ name, min, max });

export const problemCards = [
  {
    slug: 'distinct-pieces',
    title: 'Card 1 - Distinct Pieces',
    order: 1,
    difficulty: 'medium',
    points: 150,
    timeLimitMs: 2000,
    statement:
      'Every output line is a different answer for the same n. The order of the lines and the order of numbers inside a line both matter.',
    inputFormat: 'One line: one integer n',
    fields: [field('n', 1, 60)],
    hint: 'Add up the numbers on any line, and check whether any number repeats.',
    visibleInputs: ['6\n', '11\n'],
    hiddenInputs: ['45\n', '50\n', '55\n', '60\n'],
    referenceSolution: `#include <stdio.h>
static int n, part[80];

static void rec(int idx, int remaining, int maxPart) {
    if (remaining == 0) {
        for (int i = 0; i < idx; i++) printf("%d%c", part[i], i + 1 == idx ? '\\n' : ' ');
        return;
    }
    int hi = remaining < maxPart ? remaining : maxPart;
    for (int p = hi; p >= 1; p--) {
        if ((long long)p * (p + 1) / 2 < remaining) break;
        part[idx] = p;
        rec(idx + 1, remaining - p, p - 1);
    }
}

int main(void) {
    if (scanf("%d", &n) != 1) return 1;
    rec(0, n, n);
    return 0;
}
`,
  },
  {
    slug: 'no-long-runs',
    title: 'Card 2 - No Long Runs',
    order: 2,
    difficulty: 'medium',
    points: 150,
    timeLimitMs: 2000,
    statement:
      'Each line is the same length. Count how many lines you get as n grows, and look at which lines never appear.',
    inputFormat: 'One line: two integers n k',
    fields: [field('n', 1, 16), field('k', 2, 4)],
    hint: 'Only two characters are ever used. Watch what k does to the longest stretch of one of them.',
    visibleInputs: ['4 2\n', '6 3\n'],
    hiddenInputs: ['16 4\n', '15 3\n', '14 2\n', '16 2\n'],
    referenceSolution: `#include <stdio.h>
static int n, k;
static char s[32];

static void rec(int i, int run) {
    if (i == n) {
        s[n] = 0;
        puts(s);
        return;
    }
    s[i] = '0';
    rec(i + 1, 0);
    if (run + 1 < k) {
        s[i] = '1';
        rec(i + 1, run + 1);
    }
}

int main(void) {
    if (scanf("%d %d", &n, &k) != 2) return 1;
    rec(0, 0);
    return 0;
}
`,
  },
  {
    slug: 'no-echoes',
    title: 'Card 3 - No Echoes',
    order: 3,
    difficulty: 'medium',
    points: 200,
    timeLimitMs: 2000,
    statement:
      'Every line in one output has length n. Compare the lines you get with every line that could have appeared, and try k = 3 for several n.',
    inputFormat: 'One line: two integers n k',
    fields: [field('n', 1, 14), field('k', 3, 4)],
    hint: 'Look for short stretches that read the same forwards and backwards.',
    visibleInputs: ['3 3\n', '4 4\n'],
    hiddenInputs: ['14 4\n', '12 4\n', '13 3\n', '10 4\n'],
    referenceSolution: `#include <stdio.h>
static int n, k;
static char s[32];

static void rec(int i) {
    if (i == n) {
        s[n] = 0;
        puts(s);
        return;
    }
    for (int c = 0; c < k; c++) {
        char ch = (char)('a' + c);
        if (i >= 1 && s[i - 1] == ch) continue;
        if (i >= 2 && s[i - 2] == ch) continue;
        s[i] = ch;
        rec(i + 1);
    }
}

int main(void) {
    if (scanf("%d %d", &n, &k) != 2) return 1;
    rec(0);
    return 0;
}
`,
  },
  {
    slug: 'round-table',
    title: 'Card 4 - Round Table',
    order: 4,
    difficulty: 'medium',
    points: 200,
    timeLimitMs: 2000,
    statement:
      'The output is always one line holding 2m numbers. Of all valid lines, only the smallest is printed, comparing lines number by number from the left.',
    inputFormat: 'One line: one integer m',
    fields: [field('m', 1, 20)],
    hint: 'Treat the line as a circle: the last number also sits next to the first. Add each neighbouring pair.',
    visibleInputs: ['3\n', '5\n'],
    hiddenInputs: ['12\n', '15\n', '17\n', '20\n'],
    referenceSolution: `#include <stdio.h>
static int n, ring[64], used[64], isPrime[128];

static int rec(int pos) {
    if (pos == n) return isPrime[ring[n - 1] + ring[0]];
    for (int v = 2; v <= n; v++) {
        if (used[v] || !isPrime[ring[pos - 1] + v]) continue;
        used[v] = 1;
        ring[pos] = v;
        if (rec(pos + 1)) return 1;
        used[v] = 0;
    }
    return 0;
}

int main(void) {
    int m;
    if (scanf("%d", &m) != 1) return 1;
    n = 2 * m;
    for (int i = 2; i < 128; i++) {
        isPrime[i] = 1;
        for (int d = 2; d * d <= i; d++) if (i % d == 0) { isPrime[i] = 0; break; }
    }
    ring[0] = 1;
    used[1] = 1;
    rec(1);
    for (int i = 0; i < n; i++) printf("%d%c", ring[i], i + 1 == n ? '\\n' : ' ');
    return 0;
}
`,
  },
  {
    slug: 'shallow-nesting',
    title: 'Card 5 - Shallow Nesting',
    order: 5,
    difficulty: 'hard',
    points: 250,
    timeLimitMs: 2000,
    statement:
      'One number comes out. Fix n and raise d one step at a time. At n = d = 30 the answer is in the quadrillions, so it cannot be counted one arrangement at a time. Use a 64-bit integer.',
    inputFormat: 'One line: two integers n d',
    fields: [field('n', 1, 30), field('d', 1, 30)],
    hint: 'n pairs of brackets, written in a row. d limits how deep they may nest.',
    visibleInputs: ['4 2\n', '6 6\n'],
    hiddenInputs: ['30 30\n', '25 5\n', '28 3\n', '20 13\n'],
    referenceSolution: `#include <stdio.h>
static int n, d;
static long long memo[64][32];
static char seen[64][32];

static long long count(int i, int open) {
    if (i == 2 * n) return open == 0;
    if (seen[i][open]) return memo[i][open];
    long long r = 0;
    if (open < d && open < 2 * n - i) r += count(i + 1, open + 1);
    if (open > 0) r += count(i + 1, open - 1);
    seen[i][open] = 1;
    return memo[i][open] = r;
}

int main(void) {
    if (scanf("%d %d", &n, &d) != 2) return 1;
    printf("%lld\\n", count(0, 0));
    return 0;
}
`,
  },
  {
    slug: 'balanced-picks',
    title: 'Card 6 - Balanced Picks',
    order: 6,
    difficulty: 'hard',
    points: 250,
    timeLimitMs: 2000,
    statement:
      'One number comes out. Start with m = 1, then m = 2. Trying every combination works for small n but is far too slow at n = 40.',
    inputFormat: 'One line: two integers n m',
    fields: [field('n', 1, 40), field('m', 1, 40)],
    hint: 'Choose some of the numbers 1, 2, ..., n, possibly none, and add them up.',
    visibleInputs: ['4 3\n', '10 5\n'],
    hiddenInputs: ['40 7\n', '35 40\n', '40 1\n', '30 16\n'],
    referenceSolution: `#include <stdio.h>
int main(void) {
    int n, m;
    if (scanf("%d %d", &n, &m) != 2) return 1;
    unsigned long long ways[64] = {0}, next[64];
    ways[0] = 1;
    for (int i = 1; i <= n; i++) {
        for (int r = 0; r < m; r++) next[r] = ways[r] + ways[((r - i) % m + m) % m];
        for (int r = 0; r < m; r++) ways[r] = next[r];
    }
    printf("%llu\\n", ways[0]);
    return 0;
}
`,
  },
  {
    slug: 'knight-walks',
    title: 'Card 7 - Knight Walks',
    order: 7,
    difficulty: 'hard',
    points: 250,
    timeLimitMs: 2000,
    statement:
      'One number comes out. Try L = 0 and L = 1 on every board size first. At n = 12, L = 16 the count reaches trillions, so walks cannot be followed one by one.',
    inputFormat: 'One line: two integers n L',
    fields: [field('n', 3, 12), field('L', 0, 16)],
    hint: 'An n x n board, a piece that starts in a corner, and L jumps. Which chess piece has exactly 2 moves from a corner?',
    visibleInputs: ['3 2\n', '5 4\n'],
    hiddenInputs: ['12 16\n', '10 12\n', '8 14\n', '5 16\n'],
    referenceSolution: `#include <stdio.h>
int main(void) {
    int n, L;
    if (scanf("%d %d", &n, &L) != 2) return 1;
    static const int dr[8] = {1, 2, 2, 1, -1, -2, -2, -1};
    static const int dc[8] = {2, 1, -1, -2, -2, -1, 1, 2};
    long long ways[12][12] = {{0}}, next[12][12];
    ways[0][0] = 1;
    for (int step = 0; step < L; step++) {
        for (int r = 0; r < n; r++) for (int c = 0; c < n; c++) next[r][c] = 0;
        for (int r = 0; r < n; r++)
            for (int c = 0; c < n; c++) {
                if (!ways[r][c]) continue;
                for (int j = 0; j < 8; j++) {
                    int nr = r + dr[j], nc = c + dc[j];
                    if (nr >= 0 && nr < n && nc >= 0 && nc < n) next[nr][nc] += ways[r][c];
                }
            }
        for (int r = 0; r < n; r++) for (int c = 0; c < n; c++) ways[r][c] = next[r][c];
    }
    long long total = 0;
    for (int r = 0; r < n; r++) for (int c = 0; c < n; c++) total += ways[r][c];
    printf("%lld\\n", total);
    return 0;
}
`,
  },
  {
    slug: 'seating-rules',
    title: 'Card 8 - Seating Rules',
    order: 8,
    difficulty: 'hard',
    points: 300,
    timeLimitMs: 2000,
    statement:
      'One number comes out. The sequence grows unevenly: compare each odd n with the even n just before it.',
    inputFormat: 'One line: one integer n',
    fields: [field('n', 1, 20)],
    hint: 'Seat people 1..n in chairs 1..n. Each person and their chair number must get along: one divides the other.',
    visibleInputs: ['4\n', '6\n'],
    hiddenInputs: ['15\n', '17\n', '19\n', '20\n'],
    referenceSolution: `#include <stdio.h>
static long long ways[1 << 20];

int main(void) {
    int n;
    if (scanf("%d", &n) != 1) return 1;
    int full = (1 << n) - 1;
    ways[0] = 1;
    for (int mask = 0; mask < full; mask++) {
        if (!ways[mask]) continue;
        int chair = __builtin_popcount(mask) + 1;
        for (int v = 1; v <= n; v++) {
            if (mask >> (v - 1) & 1) continue;
            if (v % chair == 0 || chair % v == 0) ways[mask | 1 << (v - 1)] += ways[mask];
        }
    }
    printf("%lld\\n", ways[full]);
    return 0;
}
`,
  },
  {
    slug: 'safe-placements',
    title: 'Card 9 - Safe Placements',
    order: 9,
    difficulty: 'hard',
    points: 300,
    timeLimitMs: 3000,
    statement:
      'One number comes out. The sequence does not grow smoothly: look at what happens between 5 and 6.',
    inputFormat: 'One line: one integer n',
    fields: [field('n', 4, 14)],
    hint: 'Think of an n x n board and pieces that attack along rows, columns and both diagonals.',
    visibleInputs: ['5\n', '8\n'],
    hiddenInputs: ['11\n', '12\n', '13\n', '14\n'],
    referenceSolution: `#include <stdio.h>
static int n;
static long long total;

static void rec(unsigned cols, unsigned d1, unsigned d2, int row) {
    if (row == n) { total++; return; }
    unsigned full = (1u << n) - 1;
    unsigned avail = full & ~(cols | d1 | d2);
    while (avail) {
        unsigned bit = avail & -avail;
        avail ^= bit;
        rec(cols | bit, ((d1 | bit) << 1) & full, (d2 | bit) >> 1, row + 1);
    }
}

int main(void) {
    if (scanf("%d", &n) != 1) return 1;
    rec(0, 0, 0, 0);
    printf("%lld\\n", total);
    return 0;
}
`,
  },
  {
    slug: 'between-the-digits',
    title: 'Card 10 - Between the Digits',
    order: 10,
    difficulty: 'hard',
    points: 300,
    timeLimitMs: 2000,
    statement:
      'The output is always one expression. Try a target it can hit exactly, then one it cannot. When several expressions are equally good, only the first under a fixed order is printed.',
    inputFormat: 'One line: two integers n t',
    fields: [field('n', 1, 13), field('t', -1000, 1000)],
    hint: 'Read the digits of each line on their own: 1 2 3 4 5 6 7 8 9 1 2 3 ... Try "3 0", "3 6" and "3 12".',
    visibleInputs: ['4 10\n', '6 50\n'],
    hiddenInputs: ['12 100\n', '13 999\n', '11 -45\n', '13 -1000\n'],
    referenceSolution: `#include <stdio.h>
static int n;
static long long target, bestDiff = -1;
static char buf[64], best[64];

static void rec(int i, int len, long long total, long long cur) {
    if (i == n) {
        long long diff = total + cur - target;
        if (diff < 0) diff = -diff;
        if (bestDiff < 0 || diff < bestDiff) {
            bestDiff = diff;
            buf[len] = 0;
            for (int j = 0; j <= len; j++) best[j] = buf[j];
        }
        return;
    }
    int digit = i % 9 + 1;
    buf[len] = '+'; buf[len + 1] = (char)('0' + digit);
    rec(i + 1, len + 2, total + cur, digit);
    buf[len] = '-'; buf[len + 1] = (char)('0' + digit);
    rec(i + 1, len + 2, total + cur, -digit);
    buf[len] = (char)('0' + digit);
    rec(i + 1, len + 1, total, cur < 0 ? cur * 10 - digit : cur * 10 + digit);
}

int main(void) {
    if (scanf("%d %lld", &n, &target) != 2) return 1;
    buf[0] = '1';
    rec(1, 1, 0, 1);
    puts(best);
    return 0;
}
`,
  },
].map((card) => ({ ...card, starterCode: STARTER, status: PROBLEM_STATUS.PUBLISHED }));
